[workspace]
authors = [
  "Guillaume Quenneville <32133082+GuillaumeQuenneville@users.noreply.github.com>",
]
channels = ["conda-forge"]
name = "pixipoc"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dev]
pixipoc = { path = "." }


[package]
name = "pixipoc"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "*" }

[package.build.config]
compilers = ["cxx"]

[package.build-dependencies]
gtest = "*"
