[workspace]
authors = [
  "Guillaume Quenneville <32133082+GuillaumeQuenneville@users.noreply.github.com>",
]
channels = ["conda-forge"]
name = "pixipoc"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dependencies]
pixipoc = { path = "pixipoc" }
subpkg = { path = "subpkg" }
